plotBoxPlots([reshape(errorsPF', 1, []); reshape(errorsUPF', 1, []); reshape(errorsPFC', 1, []); ...
    reshape(errorsUPFC', 1, []); reshape(errorsPFS', 1, []); reshape(errorsUPFS', 1, [])]', ...
    [fileName, ' -- box plot of errors after ', num2str(nRuns), ' runs']);

savePlots2PDF('', [logFileName, '-results'], true);