function A = poisson(a,n,b,m)

%POISSON      Poisson matrix
%
%   A = poisson(a,n,b,m)
%
%Classical n^2 x n^2 matrix generated by  A = poisson(n+1,n,n+1,n)

% written  12/01/97     S.M. Rump
%

  if min([a,n,m,n])==1
    error('Minimum dimension in each direction is 1')
  end

  h1 = (a/(n+1))^2;
  h2 = (b/(m+1))^2;
  d1 = (h1+h2)/(h1*h2);

  e = ones(n,1);
  f = ones(m,1);
  g = zeros(n,1);
  h = zeros(m,1);
  d = ones(m*n,1);

  B = 2 * d1  * spdiags(d, 0, m*n, m*n);
  C = h1^(-1) * spdiags([-e g -e], -1:1, n, n);
  D = h2^(-1) * spdiags([-f h -f], -1:1, m, m);

  A = kron(speye(m), C) + kron(D, speye(n)) + B;

